import './globals.css'
import { DM_Sans } from 'next/font/google'

const cabin = DM_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Onyeka | MovieBox',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabin.className} >{children}</body>
    </html>
  )
}
